### ISSUE TITLE
Android pay not available 

### ISSUE THREAD

**Issue by kennedc** [tipsi/tipsi-stripe#15]
I was using react-native-billing for android pay, which was working fine on my device, but when i'm using this plugin android pay isn't available?

**Comment by fAns1k** [comment]
Hi @kennedc, thank you for your comment!
The library react-native-billing doesn't support AndroidPay.  That library uses inAppPurchases instead of Android pay, it's a different way to do payments. 
Please, install AndroidPay's app on your device to support AndroidPay.
Also, please, take into account that it's required to have NFC on your device and check if AndroidPay available for your country: https://en.wikipedia.org/wiki/Android_Pay
Read more about AndroidPay : https://developers.google.com/android-pay/tutorial

**Comment by cybergrind** [comment]
Hey @kennedc did that make sense for you? Can we close this issue?
