### ISSUE TITLE
Source: stripe got the source, but in app state source still  undefine.  

### ISSUE THREAD

**Issue by brilliantjc** [tipsi/tipsi-stripe#299]
press "Create source for Alipay payment" => auto jump to stripe web => jump back after confirming the price. 
At this moment, stripe online system shows there is a new source created, however, the source is still undefined in the app. 

<img width="537" alt="screen shot 2018-05-27 at 4 18 11 pm" src="https://user-images.githubusercontent.com/25623417/40591895-801ed61c-61cd-11e8-9c67-5fc4d8c860b2.png">

<img width="491" alt="screen shot 2018-05-27 at 4 43 24 pm" src="https://user-images.githubusercontent.com/25623417/40591899-83eb6fee-61cd-11e8-97e1-ab17d497af08.png">

<img width="556" alt="screen shot 2018-05-27 at 4 43 02 pm" src="https://user-images.githubusercontent.com/25623417/40591901-854fa404-61cd-11e8-832d-ab7a0a241003.png">

**Comment by brilliantjc** [comment]
<img width="1437" alt="screen shot 2018-05-27 at 7 36 20 pm" src="https://user-images.githubusercontent.com/25623417/40594684-6320816a-61e5-11e8-8f6f-44b2678194be.png">

**Comment by verna1228** [comment]
seems it is the stripe-ios [https://github.com/stripe/stripe-ios] sdk issue.   callback.listener(inside STPURLCallbackHandler.m > handleURLCallback function ) is not present after redirection, so it return NO.

**Comment by verna1228** [comment]
Issue fixed with following update on the library

1. open TPStripeManager.h
add this line before \@end
`@property (nonatomic) STPRedirectContext *redirectContext;`

2. open TPStripeManager.m
i. change this line   _STPRedirectContext *redirectContext = [[STPRedirectContext alloc] initWithSource:source completion:^(NSString *sourceID, NSString *clientSecret, NSError *error) {_
 to this line                 `self.redirectContext = [[STPRedirectContext alloc] initWithSource:source completion:^(NSString *sourceID, NSString *clientSecret, NSError *error) {`

3. change this line _[redirectContext startSafariAppRedirectFlow];_  into this line `[self.redirectContext startSafariAppRedirectFlow];`

then you will able to get the promise resolved.  

The reason is because of the scope of redirectContext is only inside the block.

Also if you want to have the source id, you will need to go to  TPStripeManager.m > convertSourceObject function, add this line `[result setValue:source.stripeID forKey:@"stripeID"];` after   [result setValue:source.amount forKey:@"amount"];

**Comment by NikoMontana** [comment]
@verna1228 got the solution for the undefined source. But if you "fail test payment" the promise will not get resolved again. How can I fix this problem?
