### ISSUE TITLE
Metered billing

### ISSUE THREAD

**Issue by jojonarte** [tipsi/tipsi-stripe#328]
Does this support metered billing?

**Comment by jojonarte** [comment]
@isnifer here it is https://stripe.com/docs/billing/subscriptions/metered-billing

**Comment by isnifer** [comment]
@jojonarte you have provided a link to `backend` feature. `tipsi-stripe` is a client-side library

**Comment by jojonarte** [comment]
@isnifer how do we let the client invoke a subscription to stripe?

**Comment by isnifer** [comment]
@jojonarte not sure that we have support for subscriptions. PRs are welcome!

**Comment by jlkalberer** [comment]
@jojonarte - did you ever end up figuring this out?

I think that I could probably use this library for card setup/validation and do the metered billing server-side like @isnifer suggested but I wanted to see if you made any progress.

I'm guessing that it should be app => stripe for the card token and then I can do the server-side calls after that in order to be PCI compliant?

**Comment by jojonarte** [comment]
@jlkalberer Yes I did a workaround. I just accept the cards using this library then handle metered billing on a backend server I created.
