### ISSUE TITLE
get undefined is not an object when trying to stripe.init

### ISSUE THREAD

**Issue by pmcguane** [tipsi/tipsi-stripe#53]
![simulator screen shot 16 apr 2017 6 01 45 pm](https://cloud.githubusercontent.com/assets/1862557/25069781/d9289aac-22ce-11e7-850d-004524d07b30.png)

**Comment by jsierles** [comment]
Same here.

**Comment by dmytrozavgorodniy** [comment]
Hi @pmcguane, @jsierles, how you link `tipsi-stripe` module in project? `TPSStripe.xcodeproj` is added for your main .xcodeproj?
<img width="1357" alt="screen shot 2017-04-18 at 3 49 16 pm" src="https://cloud.githubusercontent.com/assets/1718343/25131650/255be77c-244f-11e7-9431-33fce6546424.png">

**Comment by jsierles** [comment]
Sorry, I'm having this issue with Android. I have the library in my settings.gradle.

**Comment by pmcguane** [comment]
used react-native link tipsi-stripe and the file can be seen within Xcode

**Comment by dmytrozavgorodniy** [comment]
@pmcguane could to please show, how you initialize tipsi-stripe module in your project?

**Comment by jsierles** [comment]
In my case,  the following error shows up:

<img width="450" alt="screen shot on 2017-04-18 at 19-58-58" src="https://cloud.githubusercontent.com/assets/82/25199714/041aae42-254c-11e7-9bd4-aebc71882051.png">

With this initialization : 
https://gist.github.com/jsierles/ce07a9befbb1f0d34b5045d8483d7d13

**Comment by artdent** [comment]
@jsierles Have you made sure to include StripeReactPackage in the getPackages() method of your ReactNativeHost? Otherwise, NativeModules.StripeModule won't exist.

**Comment by jsierles** [comment]
@artdent Thanks, that was the problem. Working now.

**Comment by felipemartim** [comment]
@artdent Thank you very much. I don't know why this step isn't included in the Installation section of the readme.

**Comment by isnifer** [comment]
@jsierles @felipemartim Hi, guys!
This step is not included in README because this action does `react-native link`
I did clean install of react-native app and install `tipsi-stripe`. Look into gif:
![react-native-link](https://cloud.githubusercontent.com/assets/1788245/25302902/51e738dc-2751-11e7-9db8-144f49542d62.gif)

Info about linking dependencies in README:
* https://github.com/tipsi/tipsi-stripe#ios-1
* https://github.com/tipsi/tipsi-stripe#android-1

**Comment by felipemartim** [comment]
@isnifer Maybe because I use React Native Navigation this step didn't work. Anyway, I think it could be added on the manual installation section.

**Comment by artdent** [comment]
Right, `react-native link` might fail for a variety of reasons; for example, in my project, the android project is at the top level instead of being inside an `android/` directory. (Not to mention, my ReactNativeHost is a top-level class instead of an inner class.) So the manual instructions, along with describing the modifications to build.gradle, should also include the step of modifying `getPackages()`.

**Comment by isnifer** [comment]
@felipemartim @artdent Hey, guys! I've added a PR that will improve README.
