### ISSUE TITLE
ios build issue

### ISSUE THREAD

**Issue by shauntomy** [tipsi/tipsi-stripe#711]
I am having an issue when building ios in Release configuration.

I am getting the following error:

```
ld: building for iOS Simulator, but linking in object file built for iOS, file '~/path/to/file/ios/Pods/Stripe/InternalFrameworks/libStripe3DS2.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I can't seem to figure out what the issue is at all. Please help.

**Comment by joshua-hester** [comment]
Did you run Pod install in the iOS folder?

**Comment by shauntomy** [comment]
Yes, I had ran pod install and cleaned the build folder before I ran it. However, when it gets to the Stripe bit, it fails. It runs completely fine in debug mode though. No issues at all.

**Comment by teamzz111** [comment]
Try with pyshical device.

**Comment by Aeyzaz** [comment]
Run Xcode with Rosetta 2

**Comment by pehagg** [comment]
> Run Xcode with Rosetta 2

Works only for Apple silicon.

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
