### ISSUE TITLE
Stripe connect account using firebase cloud functions

### ISSUE THREAD

**Issue by jaysoni9294** [tipsi/tipsi-stripe#727]
i want to create multiple business  account with One main account using firebase cloud functions ,how can we achieve this ?

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
