### ISSUE TITLE
Throw warning if strip.init is called with bad parameters

### ISSUE THREAD

**Issue by scottyantipa** [tipsi/tipsi-stripe#73]
See https://github.com/tipsi/tipsi-stripe/issues/34
This is currently closed, but only because the author figured out the root cause.  It would be nice if `stripe.init` inspected arguments and threw a warning before passing them to the native module.

**Comment by itsmepetrov** [comment]
Hi @scottyantipa, thank you for your comment. We will update init method later.

**Comment by ronitslyper** [comment]
There's an article on medium.com https://medium.com/code-well-live-forever/credit-cards-with-stripe-and-react-native-1bfe9afcbb42  , shows up second result in google for tipsi-stripe, has an error in the init function (publishable_key instead of publishableKey). Bad init gives the nil argument exception ...  might want to keep an eye out for this as a source of Issues.

**Comment by isnifer** [comment]
@ronitslyper thanks for sharing, I wrote request to the author to change his tutorial.
