### ISSUE TITLE
Achieving a marketplace using tipsi-stripe

### ISSUE THREAD

**Issue by AJ-Benoit** [tipsi/tipsi-stripe#731]
Hi, is it possible to use the tipsi-stripe library to achieve a marketplace in React Native? That is to collect payments from one user and then payout to another. If so, how can I possibly go about achieving this? Thanks

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
