### ISSUE TITLE
how to close the 3d secure page automatically 

### ISSUE THREAD

**Issue by Hammam94** [tipsi/tipsi-stripe#734]
how to close the 3d secure page automatically after authenticated is complete without user interaction on the close or done button?

**Comment by joeybronner** [comment]
up 🤞

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
