### ISSUE TITLE
Build failed on iOS Undefined symbol: _swift_getOpaqueTypeConformance

### ISSUE THREAD

**Issue by jp928** [tipsi/tipsi-stripe#742]
## The problem
Build failed

## Environment
* `tipsi-stripe` version: 9.0.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: iOS
* OS version: MacOS
* React-Native version: 0.64

##
```
Undefined symbol: _swift_getOpaqueTypeConformance
```

If remove library_search_path, like mentioned here:
https://github.com/react-native-community/upgrade-support/issues/62

then react-native-linear-gradient failed in build. 

```
Library not found for -lBVLinearGradient
```

**Comment by Jpoliachik** [comment]
I'm getting this error too. Using Xcode 12.4, with ReactNative 0.63.4, and `tipsi-stripe: ^9.0.0`
App built fine before. But immediately after `yarn add tipsi-stripe` and `pod install` I start getting these build errors.

**Comment by Jpoliachik** [comment]
I think the root issue is related to Stripe's recent iOS SDK 21.x update, and their switch to Swift. See https://stripe.com/docs/mobile/ios/sdk-21-migration

I got my build working as a workaround by downgrading `tipsi-stripe` to `8.0.2`, and I also had to explicitly install Stripe `pod 'Stripe', '19.0.1'` in my Podfile, otherwise `tipsi-stripe` would include the latest Stripe version, which we don't want.

**Comment by jp928** [comment]
@JonghunYu Thanks for sharing your solution. It is most likely the solution by far.

**Comment by zztczcx** [comment]
@JonghunYu  Thanks. I tried yarn add tipsi-stripe 8.0.2 and cd ios & pod install (Stripe 19.4.0), which also builds successfully.

**Comment by andrea-provenzale** [comment]
I managed to make it work by removing "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)" line from LIBRARY_SEARCH_PATHS in project.pbxproj file, as mentioned here: 
https://github.com/react-native-community/upgrade-support/issues/62

**Comment by seamive** [comment]
So no way to `tipsi-stripe 9.0.0` with `Stripe 21.4.0` except downgrading??

**Comment by zhahaoyu** [comment]
Only removing "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)" this does not solve the problem.

I had to do the following to resolve the issue completely

>Removed all entries from LIBRARY_SEARCH_PATHS in the Project configuration
Add a new Swift file to the project (File > New > File > Swift), and call it whatever you want

**Comment by babyrusa** [comment]
I'm on `tipsi-stripe 9.0.0` with Stripe `21.6.0` but still experience building errors on XCode. I will try to downgrade

**Comment by minh-dai** [comment]
same +1 :(((

**Comment by emernuness** [comment]
Same from me

**Comment by bonnmh** [comment]
error build: Undefined symbol: _swift_getOpaqueTypeConformance

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
