### ISSUE TITLE
How to recollect a cvc for a saved card?

### ISSUE THREAD

**Issue by dmc1985** [tipsi/tipsi-stripe#747]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I would like to allow payments with a saved card stored in the backend but I want the user to reenter the cvv of the saved card as an extra fraud prevention measure. How can I do this? I don't see anything about this in the doc and `confirmPaymentIntent` requires me to either pass the `paymentMethodId` or all the credit card info in the `paymentMethod` param. However, I cannot just pass the cvv in `paymentMethod` along with `paymentMethodId`.

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
