### ISSUE TITLE
build example of 8.0.2

### ISSUE THREAD

**Issue by zztczcx** [tipsi/tipsi-stripe#752]
no matter yarn install or npm install , it only succeeds after commenting appium and appium-helper.
I also need to change the target of ios to 10 to make sure the pod can install.

all these are done, you can run-ios happily .

I think we need to fix appium's version .

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
