### ISSUE TITLE
MerchantId is required

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [tipsi/tipsi-stripe#757]
Hi, 

you are saying that merchant id is required if people want to use Apple Pay
https://tipsi.github.io/tipsi-stripe/docs/usage.html

but stripe says that it does not expose merchant id.  
https://support.stripe.com/questions/merchant-account-number-or-merchant-id-for-sellers-permit-applications

So whee is the truth?

**Comment by plowman** [comment]
@vytautas-pranskunas- I think there is more than one meaning of the term "Merchant ID", and Stripe is referring to a different meaning.

If you want to use Apple Pay, you have to specify your Apple Merchant ID, which is the Certificate Name of your Apple Pay Payment Processing certificate in your [Apple Developer Account](https://developer.apple.com/account/resources/certificates/list). Usually this is something like "merchant.your.bundle.id".

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
