### ISSUE TITLE
Getting 'There was an unexpected error, please try again in a few seconds' error on 3d secure flow

### ISSUE THREAD

**Issue by mudassar6969** [tipsi/tipsi-stripe#774]
We have implemented stripe 3d secure flow in our app but it's not working on some live cards when collecting payments. When we get clientSecret against the payment from the server and calls authenticatePaymentIntent method with the client secret, we get an exception 'There was an unexpected error, please try again in a few seconds'.  Any help would be much appreciated.

**Comment by prashantvv** [comment]
getting same with  "tipsi-stripe": "^9.1.4", platform :ios, '11.0' xcode- 12.4. Need solution or hv to downgrade to lover version somewhere to 8.x.x which is now not supported by android playstore and will not allow uploading that apk

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
