### ISSUE TITLE
google pay in IOS

### ISSUE THREAD

**Issue by mayur2345** [tipsi/tipsi-stripe#777]
Is it possible to implement google pay in IOS simulator using tipsi stripe?

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
