### ISSUE TITLE
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by usmanghani720** [tipsi/tipsi-stripe#781]
[](url)
![Screenshot from 2021-05-20 15-03-48](https://user-images.githubusercontent.com/26020228/118960398-b1807080-b97c-11eb-97d9-76d1a52190ae.png)

**Comment by usmanghani720** [comment]
I get this issue when I have installed tipsi stripe in my react native app and import it in one of the components. Can somebody help me out what I am missing here

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
