### ISSUE TITLE
Android -  Previous state of stripe payment screen not getting When app reopen click of app icon after minimize 

### ISSUE THREAD

**Issue by RajeshRRathod** [tipsi/tipsi-stripe#794]
## The problem
Here when i am performing 3d secure payment using stripe payment screen.When i  minimize the application in between this process and ,reopen it by clicking on app icon at that time i am not getting previous state of stripe payment screen specific for android.
issue link : https://drive.google.com/file/d/1cYpyo-8WQOy_zHotEPvtGb97rr9ZT40w/view

## Environment
* `tipsi-stripe` version: 8.0.0-beta.10
* iOS or Android: Android
* OS version:  OS 9 
* React-Native version: 0.62.2

* android.compileSdkVersion :29
* android.buildToolsVersion :29.0.2
* android.defaultConfig.minSdkVersion :21
* android.defaultConfig.targetSdkVersion :29 
* android.defaultConfig.multiDexEnabled (if exists) : true

## Code To Reproduce Issue (Good To Have)
const auth3DResponse = await stripe.authenticatePaymentIntent({
              clientSecret: client_secret,
            });

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
