### ISSUE TITLE
null is not an object evaluating (StripeModule.init )  react native ios

### ISSUE THREAD

**Issue by zaidmunir11s** [tipsi/tipsi-stripe#802]
null is not an object evaluating (StripeModule.init )  react native ios

I cannot find solution of this error which i get only in ios version. In android it is working fine

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
