### ISSUE TITLE
Apple Pay Issue

### ISSUE THREAD

**Issue by kishoreAwdar** [tipsi/tipsi-stripe#811]
Apple pay is working on simulator without any issues, but on real phones (include sandbox account and live account) doesn't work.
It shows an alert "Error: Cancelled by user". (please check the image).

App region is 'Ireland'.
Created everything for Apple Pay.

My code is below

***
import RNPickerSelect from 'react-native-picker-select';
stripe.setOptions({
  publishableKey: 'pk_test_*********************************',
  merchantId: 'merchant.com.--.--------',
})

try {
      const token = await stripe.paymentRequestWithNativePay({
            currencyCode: 'EUR',
            countryCode: 'IE',
            shippingType:'delivery',
            requiredBillingAddressFields: [],
          },
          [
            {
              label: 'Item',
              amount: '' + totalPrice,
            }
          ],
      );

![IMG-20210723-WA0031 (1)](https://user-images.githubusercontent.com/30290681/126858789-93c1ea8b-b841-4560-9625-25863fea295a.jpg)

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
