### ISSUE TITLE
do we need certificate to use paymentRequestWithNativePay 

### ISSUE THREAD

**Issue by ziga-hvalec** [tipsi/tipsi-stripe#822]
Hi

I'm using paymentRequestWithNativePay to open the apple pay and get user's credit card info.  https://tipsi.github.io/tipsi-stripe/docs/paymentRequestWithNativePay.html
Currently we are only using apple pay to get the credit card info.

Do I need to upload my merchant certificate to stripe. Or do I only need this if I want to make payments with apple pay?

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
