### ISSUE TITLE
authenticatePaymentIntent on connect account iOS not working on 3DS cards

### ISSUE THREAD

**Issue by Sherby1988** [tipsi/tipsi-stripe#824]
## The problem
I use stripe with stripe connect and everything works except this when I try to authenticatePaymentIntent a payment with a card that uses 3d secure, but this only happens on iOS, on android everything works fine. 
I use setStripeAccount before the authenticatePaymentIntent function.
What is strange is that after I make a payment using native apple pay, then everything works ok using the 3ds card.
From what I see the setStripeAccount function does not apply on authenticatePaymentIntent but only after paymentRequestWithNativePay is complete.

## Environment
* `tipsi-stripe` version: 9.1.4
* iOS or Android: iOS
* OS version: 15
* React-Native version: 0.63.4

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
