### ISSUE TITLE
Application hangs when I try to add the card details.

### ISSUE THREAD

**Issue by Hari-krish-v** [tipsi/tipsi-stripe#836]
Application is being stuck when I try to add the card details on PaymentCardTextField the issue is only on iOS device.

Issue is not showing when I open the application on Stimulator.

The packages and version I have used 
"tipsi-stripe": "^9.2.0"

**Comment by stewartmcgown** [comment]
This package is deprecated, migrate to https://github.com/stripe/stripe-react-native

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
