### ISSUE TITLE
Can't build app with xcode 14

### ISSUE THREAD

**Issue by xuanduyrn** [tipsi/tipsi-stripe#845]
1. `"tipsi-stripe": "10.0.0"`
2. Podfile `pod 'Stripe', '~> 21.3.1'`
3. xcode 14 (ios 16)
4. Error: `/ios/Pods/Stripe/Stripe/`

`STPAddCardViewController.swift:118:4: error: stored properties cannot be marked potentially unavailable with '@available'
  @available(iOS 13, *)
   ^
/ios/Pods/Stripe/Stripe/STPAddressFieldTableViewCell.swift:23:48: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
protocol STPAddressFieldTableViewCellDelegate: class {
                                               ^~~~~
                                               AnyObject
/ios/Pods/Stripe/Stripe/STPAddressViewModel.swift:13:39: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
protocol STPAddressViewModelDelegate: class {
                                      ^~~~~
                                      AnyObject
ios/Pods/Stripe/Stripe/STPBSBNumberValidator.swift:133:42: warning: 'IndexDistance' is deprecated: All index distances are now of type Int
private let kBSBNumberDashIndex = String.IndexDistance(3)`

**Comment by Adrianbigwig** [comment]
Having similar issue.

**Comment by dannydanzka** [comment]
For my situation, I can't to update to the official library stripe because my version for React Native 0.63.4 doesn't support.

I write the solution that worked from me.

"tipsi-stripe": "9.2.0"
Podfile pod 'Stripe', '~> 22.8.2'
xcode 14.2
Update version in Podfile platform :ios, '12.0'
Reset pods cd ios && rm -rf Pods/ Podfile.lock && pod install --repo-update
