### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by diego-caceres** [tipsi/tipsi-stripe#97]
Hi, I'm using the paymentRequestWithCardForm method to show the Stripe pop up so that the user can enter his credit card information in order to get the Token. 
The problem I have is that even though the device language is in Spanish, the title and buttons are in english ("Enter your card" in android, and "Add a card" in iOS). I can see that the project has Localizable.strings but I'm missing if there's a way to set the language. In my case, all the users will be spanish speakers (Almost 100%)

Thanks for any guidance.

**Comment by isnifer** [comment]
Hi @diego-caceresm, good question! We didn't add l10n into the component yet. Need time to investigate.

**Comment by RiusmaX** [comment]
+1 for i18n support, need to translate in 12 langages, maybe adding some props or some options with texts  and labels ?

Thanks for your work !

**Comment by isnifer** [comment]
@RiusmaX PRs welcome!

**Comment by diego-caceres** [comment]
Hi @isnifer ! I'm willing to try to add this feature, but do you have some guidance? The thing is that I have downloaded the project and I don't seem to find where the "texts" are. So far I have only found the ones in the strings.xml of the android project (which I'm not sure are all of them), but none on the iOS one. Do you hace any idea what I might be missing? 

Thanks

**Comment by isnifer** [comment]
Hi, @diego-caceres currently there is no place for that. I will investigate how to do it better today. Stay tuned!

**Comment by jbouaziz** [comment]
Hey! Have you guys made any progress on this particular issue?

**Comment by syzer** [comment]
👍

**Comment by cauboy** [comment]
👍

**Comment by melvinxie** [comment]
👍

**Comment by juergengunz** [comment]
👍

**Comment by isnifer** [comment]
@syzer @cauboy @melvinxie @juergengunz PRs are welcome!

**Comment by syzer** [comment]
We decided to re due whole screen... to match our UX guidelines

**Comment by xenobarbital** [comment]
Commenting here to avoid duplicating. Is the localization implemented yet?

**Comment by cybergrind** [comment]
@xenobarbital there are no ongoing PR's with that

**Comment by yassinecc** [comment]
Hi @diego-caceres, you can easily add language support on iOS, Android requires a bit more effort:

- **iOS:**
`paymentRequestWithCardForm` uses the native card modal provided in the Stripe iOS SDK which support [a number of languages](https://stripe.com/docs/checkout#supported-languages) out of the box, you will just need to set up your app to support internationalization.

In the Info tab of your XCode project, make sure you have checked the "Base Internationalization" box in the "Loclizations" sections (1), and add the languages you want to support to the Languages list (2) cf. screenshot
<img width="1542" alt="screen shot 2018-11-24 at 12 52 12" src="https://user-images.githubusercontent.com/31844581/48967912-16df8a80-efe8-11e8-9003-ebdcf5fc393f.png">

- **Android:**
`paymentRequestWithCardForm`uses a 3rd party [card entry library](https://github.com/tipsi/CreditCardEntry) which needs specific locale resources.

  - First open a pull request on https://github.com/tipsi/CreditCardEntry like [this one](https://github.com/tipsi/CreditCardEntry/pull/7/files) with the language you want to have support of instead of French.
  - Then open another one on this repo like #395 with your language of choice

**Comment by acro5piano** [comment]
@yassinecc 
Thank you for your suggestion. That's very helpful!

In Android, we can add our own launguage support without creating Pull Request by adding our original strings file to `android/app/src/main/res/values-**/strings.xml`. For example, if you add Japanese support then create `android/app/src/main/res/values-ja/strings.xml` with the following XML file, and build RN app. It will be translated.

```xml
<resources>

  <string name="gettipsi_card_number">カード番号</string>
  <string name="gettipsi_save">保存</string>
  <string name="gettipsi_card_cvc">確認番号（CVC）</string>
  <string name="gettipsi_google_pay_unavaliable">この端末では、 Google Pay はご利用になれません。</string>
  <string name="gettipsi_user_cancel_dialog">キャンセルしました。カードは追加されていません。</string>
  <string name="gettipsi_card_enter_dialog_title">カード番号を入力して下さい</string>
  <string name="gettipsi_card_enter_dialog_positive_button">完了</string>
  <string name="gettipsi_card_enter_dialog_negative_button">キャンセル</string>
  <string name="gettipsi_card_number_label">カード</string>

  <string-array name="gettipsi_currency_array">
    <item>通貨 (任意)</item>
    <item>指定しない</item>
    <item>円</item>
  </string-array>
</resources>
```

In this way, we don't have to wait a new version, and customize strings as much as we want.

However, out-of-box solution is better for developers, so I will try to create PR as @yassinecc suggested.

**Comment by filipepiresg** [comment]
for me, this @acro5piano solution worked, just the "Expiration date" field that I didn't find where to switch.

Thank you

**Comment by JB-CHAUVIN** [comment]
I didn't get how to translate Stripe's API responses ?

**Comment by LokmaneKrizou** [comment]
@filipepiresg  same with me, did you have any chance to solve it?

**Comment by badpenguin** [comment]
Anybody knows the android's string for the "expiration date" ?

**Comment by badpenguin** [comment]
Ok got it! Those works for android! https://github.com/tipsi/CreditCardEntry/blob/master/CreditCardEntry/res/values/strings.xml
